### ISSUE TITLE
Problem with installation (bolt-translate extension)

### ISSUE THREAD

**Issue by Snickerss** [AnimalDesign/bolt-translate#18]
Hello. 
I want to use the Translation plugin in my BOLT project.

I setup bolt-translate extension and done steps from "read me".

I dont understand # 8 step (Translate your boltforms by adding {% set form = translate_form(form) %} at the top of a form template. This requires the labels extension. (the current solution is very hacky, WIP)) and # 9 step (If you use the menueditor extension it will automatically add fields for translated labels, use these by adding {{ item[app.request.get('_locale')~'label'] ?: item.label|default('-') }} in your menu template.)

In what files I need to write down the code, in order to get "select the languages" in the form of creating / editing the contenttype entityes (as in your example - https://cloud.githubusercontent.com/assets/343392/10799822/23900e48-7daf-11e5-86ad-c7f7730a0b13.png) ?

**Comment by SahAssar** [comment]
Hey @Snickerss,

# 8 is "optional" and you only need to do it if you use the boltforms extension to make contact forms or similar things and want those to have translated placeholders/labels.

# 9 is also optional since it's only if you want your menu to have translated labels shown.

Both require modification of templates (the .twig files in your theme), so if that's not your thing you can just ignore them.

**Comment by SahAssar** [comment]
> In what files I need to write down the code, in order to get "select the languages" in the form of creating / editing the contenttype entityes 

If you just follow all the other steps you will get that.
