### ISSUE TITLE
How do you output other language urls for the same page?

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#3]
I want to implement a language menu where you can switch language. Is it possible to output urls for the same page? Something like this:

domain/en/hello-world
domain/nl/hallo-wereld
domain/de/hallo-weld

**Comment by SahAssar** [comment]
Have you tried the using the `{{ localeswitcher()|raw }}` in your template? That should output a languageswitcher that uses the localized slugs for each language.

**Comment by Puddingboy** [comment]
Ohw crap, this is embarrassing. It's also on the front page of this github depository. I feel like I've lived my life in a cage. o.O

Do you also have suggestions on translating image file name and the image alt text/title without having to reupload the file?

**Comment by SahAssar** [comment]
Haha, No problem, I was just beginning to think I broke it up somehow :smile: 

About the images:

The easiest way is probably to use the stack. It should include the latest uploaded files, so just clicking "select from stack" should show the latest 10 or so images you have uploaded. Otherwise you can use "select from server". Those two assume that you are fine with having one file-name for all languages, which should cover 99% of use-cases. If you want translated file-names you will have to upload one file per language. Alt/title text translation should be supported automatically.

Also, I'd be very interested in hearing about any bugs or kinks that you come across in the extension since it hasn't really been battle-tested yet.

**Comment by Puddingboy** [comment]
I've not really come across bugs, but I did make a few small observations, while running through the steps. While not running into bugs, I did encounter other interesting stuff. I get the suggestion to update the database. This seems harmless to me, I did and it fixed stuff. Also installing is not possible without all extension subfiles having 777 permission. While I did set the parentfolder(extensions) to 777, subfolders were ignored in my ftp program. I should really get into the use of command line.

**Comment by SahAssar** [comment]
Hmm, those are mostly things regarding bolt itself, not this extension specifically... I'm guessing that you haven't used bolt extensively before?

**Comment by Puddingboy** [comment]
Actually I just started using bolt, but I'm starting to like it more and more. Sorry if I haven't been of any good use.

**Comment by SahAssar** [comment]
No, I didn't mean that it wasn't helpful!

Please feel free to ask/comment here on github or in the IRC/slack channels if you run into any future problems :)
