### ISSUE TITLE
Homepage redirect no longer working

### ISSUE THREAD

**Issue by SahAssar** [AnimalDesign/bolt-translate#47]
Homepage redirect no longer working since the homepage gets a default _locale since #43.

Possible duplicate content issue since the same page will happily display on both `/` and `/{default_locale_here}` (with different canonicals).

Details
-------

 - Translate Version: master 
 - Install type: Extension Repository
 - Bolt Version: master

**Comment by peterverraedt** [comment]
I should have known this, I encountered the same bug before in my early attempt to port the extension to bolt 3.0. The best solution is to remove the default _locale, and to make sure that the `_locale` parameter is always set in the url_generator's context, since that was the main reason to put a default value. I'll post a pull request in a minute.
