### ISSUE TITLE
[BUG] InvalidParameterException and Uncaught Exception: HttpException

### ISSUE THREAD

**Issue by nestordedios** [AnimalDesign/bolt-translate#92]
Hi everyone,

I'm having some troubles with the extension and it is not working as expected for me.

I have set Dutch as default locale and added English as a second language for the site.

When I create a new page and fill in some fields the dutch version looks like this

![new-page](https://cloud.githubusercontent.com/assets/6607455/21313788/252ed20a-c5f4-11e6-9df6-3142292689c0.png)

the English version looks like this

![new-page-en](https://cloud.githubusercontent.com/assets/6607455/21313859/717ba728-c5f4-11e6-8af1-f08f05631c9d.png)

When I try to go to /nl/page/test-in-dutch I get this error

![invalidparameter](https://cloud.githubusercontent.com/assets/6607455/21314007/0f28dbe4-c5f5-11e6-8275-c0d70bac4d07.png)

and going to /en/page/test-in-dutch ends up in another error message

![exception](https://cloud.githubusercontent.com/assets/6607455/21314035/2fd50610-c5f5-11e6-80e6-459f952c26b1.png)

In the backend again, if I go to the English version of the page I just created, without editing anything I hit the Save button... Both pages are now visible in the browser

Of course, this is not what I expected. For me it won't be necessary to have an English version of all pages I create. 

In my opinion just creating a page in my default locale with no content in other languages should keep things working when I try to visit the page I just created. Is there something I'm missing to accomplish that @SahAssar ?

Details
-------

 - Translate Version: [ 4.0.1 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.2.3 ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache 2.2.22   ]

**Comment by sbonardt** [comment]
I have the same issue:

I think the ERROR description would be: Saved page not accessible after 'publication' and 'save' when multiple langs specified. The error page above is shown.

I have the same version as @nestordedios and setup the same way.

If i create a page, there are no options for multi language because the page has not been saved yet. After saving/publication the tab with the langs appears in the backend. However, if I want to view the saved page it is not possoible, with the resulting error above. When I go back to the backend and click the other lang tab and press save for that lang the item gets saved.

If I reload the page to view it, it loads OK, in both languages.

It seems like a problem with saving the content and publishing the slugs when we have multiple langs... :\

**Comment by madc** [comment]
If `translate_slugs` is set to true in the extension config, a separate `slug` field for each locale (`en_slug`, `de_slug`,...) is created. It seems, that only the default locale is populated, the others are left empty.
